**A. Каждому по компьютеру**
В новом учебном году на занятия в компьютерные классы Дворца Творчества Юных пришли учащиеся, которые были разбиты на N групп. В i-й группе оказалось Xi человек. Тут же перед директором встала серьезная проблема: как распределить группы по аудиториям. Во дворце имеется M ≥ N аудиторий, в j-й аудитории имеется Yj компьютеров. Для занятий необходимо, чтобы у каждого учащегося был компьютер и еще один компьютер был у преподавателя. Переносить компьютеры из одной аудитории в другую запрещается. Помогите директору!

Напишите программу, которая найдет, какое максимальное количество групп удастся одновременно распределить по аудиториям, чтобы всем учащимся в каждой группе хватило компьютеров, и при этом остался бы еще хотя бы один для учителя.

**Формат ввода**
На первой строке входного файла расположены числа N и M (1 ≤ N ≤ M ≤ 1000). На второй строке расположено N чисел — X1, …, XN (1 ≤ Xi ≤ 1000 для всех 1 ≤ i ≤ N). На третьей строке расположено M чисел Y1, ..., YM (1 ≤ Yi ≤ 1000 для всех 1 ≤ i ≤ M).

**Формат вывода**
Выведите на первой строке число P - количество групп, которые удастся распределить по аудиториям. На второй строке выведите распределение групп по аудиториям – N чисел, i-е число должно соответствовать номеру аудитории, в которой должна заниматься i-я группа. (Нумерация как групп, так и аудиторий, начинается с 1). Если i-я группа осталась без аудитории, i-е число должно быть равно 0. Если допустимых распределений несколько, выведите любое из них.

**Пример**
Ввод: 
1 1
1
2

Вывод:
1
1

In [ ]:
N, M = map(int, input().split())
data_x = list(map(int, input().split()))
data_y = list(map(int, input().split()))
data_x, idx_x = zip(*sorted(zip(data_x, [i for i in range(N)])))
data_y, idx_y = zip(*sorted(zip(data_y, [i for i in range(M)])))
ans = [0] * N
s, k = 0, 0
for i in range(len(data_x)):
    while s < len(data_y) and data_y[s] <= data_x[i]:
        s += 1
    if s == len(data_y):
        break
    ans[idx_x[i]] = idx_y[s] + 1
    k += 1
    s += 1
print(k)
print(*ans)

**B. Квадрат из 0 и 1**
Требуется в каждую клетку квадратной таблицы размером NxN поставить ноль или единицу так, чтобы в любом квадрате размера KxK было ровно S единиц.

**Формат ввода**
Во входном файле записаны три числа — N, K, S (1≤ N ≤ 100, 1 ≤ K ≤ N, 0 ≤ S ≤ K2).

**Формат вывода**
В выходной файл выведите заполненную таблицу. Числа в строке должны разделяться пробелом, каждая строка таблицы должна быть выведена на отдельной строке файла. Если решений несколько, выведите любое из них.

**Пример**
Ввод: 
4 2 2

Вывод:
1 0 0 1
0 1 1 0
1 0 0 1
0 1 1 0

In [ ]:
def watch_table(data, n, k):
  for i in range(n // k):
    for j in range(len(data)):
      print(*(n // k * data[j]), sep=" ", end=" ")
      print(*data[j][0:n % k], sep=" ")

  for i in range(n % k):
    print(*(n // k * data[i]), sep=" ", end=" ")
    print(*data[i][0:n % k], sep=" ")


n, k, s = map(int, input().split())
data = [[0] * k for _ in range(k)]
square_sum = 0
for i in range(len(data)):
    for j in range(len(data[i])):
        if square_sum == s:
            break
        data[i][j] = 1
        square_sum += 1
watch_table(data, n, k)

**C. Интернет**
Новый интернет-провайдер предоставляет услугу доступа в интернет с посекундной тарификацией. Для подключения нужно купить карточку, позволяющую пользоваться интернетом определенное количество секунд. При этом компания продает карточки стоимостью 1, 2, 4, …, 230 рублей на a0, a1, a2, …, a30 секунд соответственно.

Родители разрешили Пете пользоваться интернетом M секунд Определите, за какую наименьшую сумму он сможет купить карточки, которые позволят ему пользоваться интернетом не менее M секунд. Естественно, что Петя может купить как карточки различного достоинства, так и несколько карточек одного достоинства.

**Формат ввода**
В первой строке содержится единственное натуральное число M (1 ≤ M ≤ 109). Во второй строке задаются натуральные числа a0, a1, …, a30, не превосходящие 109.

**Формат вывода**
Выведите единственное число – наименьшую сумму денег, которую Пете придется потратить.

**Пример**
Ввод: 
11
1 1 10 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

Вывод:
5

In [ ]:
m = int(input())
data = list(map(int, input().split()))
k = 0
for i in range(1, 31):
    if data[i - 1] * 2 > data[i]: data[i] = data[i - 1] * 2
for i in range(30, -1, -1):
    if data[i] <= m: m, k = m - data[i], k + 2 ** i
if m > 0: k += 1
print(k)

**D. Турнир**
В турнире по хоккею участвовало K команд, каждая сыграла с каждой по одному матчу. За победу команда получала 2 очка, за ничью – 1, за поражение – 0 очков.

Известно, сколько очков в итоге получила каждая команда, однако результаты конкретных матчей были утеряны. Требуется восстановить одну из возможных турнирных таблиц.

**Формат ввода**
В первой строке входных данных содержится одно натурально число K, не превосходящее 100 – количество команд. Во второй строке задаются через пробел K целых неотрицательных чисел, не превосходящих 2(K–1), – количество очков, набранных командами, занявшими первое, второе, …, K-е места соответственно (то есть каждое следующее число не больше предыдущего).

**Формат вывода**
Выведите турнирную таблицу в следующем формате. Таблица должна состоять из K строк с результатами игр команд, занявших первое, второе, …, последнее место (команды, набравшие одинаковое число очков, могут быть расположены в таблице в любом порядке). В каждой строке должно быть записано K чисел через пробел – количество очков, набранных в игре данной команды с первой, второй, … командами соответственно. Количество очков – это число 0, 1 или 2. В клетках на главной диагонали (соответствующих не существующей игре команды "самой с собой") нужно записать нули.

Гарантируется, что входные данные соответствуют реальному турниру, то есть хотя бы одна таблица, соответствующая входным данным, может быть построена. Если таких таблиц несколько, выведите любую из них.

**Пример**
Ввод: 
4
6 4 2 0

Вывод:
0 2 2 2 
0 0 2 2
0 0 0 2
0 0 0 0

In [ ]:
def tur(data1, data2):
    for j in range(i + 1, n):
        if data[data2[i]][data2[j]] > 0:
            continue
        elif data1[i] > 0:
            data[data2[i]][data2[j]] = 1
            data[data2[j]][data2[i]] = 1
            data1[i] -= 1
            a[data2[j]] -= 1
        elif data1[i] == 0:
            data[data2[j]][data2[i]] = 2
            a[data2[j]] -= 2


n = int(input())
a = list(map(int, input().split()))
d = [i for i in range(n)]
data = [[0] * n for _ in range(n)]
for i in range(n - 1):
    data_a, data_d = zip(*sorted(zip(a, d)))
    data_a, data_d = list(data_a), list(data_d)
    tur(data_a, data_d)
    a[data_d[i]] = -i - 1
for i in range(n):
    print(*data[i])

**E. Приключение**
Теплым весенним днем группа из N студентов-программистов гуляла в окрестностях города Одинцово. К несчастью, они набрели на большую и довольно глубокую яму. Как это случилось — непонятно, но вся компания оказалась в этой яме.

Глубина ямы равна H. Каждый студент знает свой рост по плечи hi и длину своих рук li. Таким образом, если он, стоя на дне ямы, поднимет руки, то его ладони окажутся на высоте hi + li от уровня дна ямы. Студенты могут, вставая друг другу на плечи, образовывать вертикальную колонну. При этом любой студент может встать на плечи любого другого студента. Если под студентом i стоят студенты j1, j2, …, jk, то он может дотянуться до уровня

hj1 + hj2 +...+ hjk + hji + li.

Если студент может дотянуться до края ямы (то есть
hj1 + hj2 +...+ hjk + hji + li >= H), то он может выбраться из нее. Выбравшиеся из ямы студенты не могут помочь оставшимся.

Найдите наибольшее количество студентов, которые смогут выбраться из ямы до прибытия помощи, и перечислите их номера.

**Формат ввода**
В первой строке входных данных задается натуральное число N (1 ≤ N ≤ 2000) — количество школьников, попавших в яму.

Далее в N строках содержится по два целых числа: рост i-го студента по плечи hi (1 ≤ hi ≤ 105) и длина его рук li (1 ≤ li ≤ 105).

В последней строке указано целое число — глубина ямы H (1 ≤ H ≤ 105).

**Формат вывода**
В первой строке выведите K — максимальное количество студентов, которые смогут выбраться из ямы. Если K > 0, то во второй строке в произвольном порядке выведите их номера, разделяя их пробелами. Студенты нумеруются с единицы в том порядке, в котором они заданы во входных данных. Если существует несколько решений, выведите любое.

**Пример**
Ввод: 
70
14 434
9 105
13 61
5 495
12 13
6 922
20 197
14 661
14 907
15 490
15 305
7 765
4 833
8 691
22 352
6 478
18 205
8 539
4 507
7 637
11 459
3 254
31 596
17 712
1 260
24 666
22 804
12 323
22 610
52 765
15 286
4 448
22 76
8 961
33 44
26 124
28 227
5 372
7 729
7 645
5 483
5 974
18 933
5 967
2 975
16 186
15 524
4 36
24 419
26 143
1 559
16 942
45 866
15 693
22 978
10 287
32 377
14 542
14 858
10 118
4 242
24 333
12 463
22 568
10 510
6 732
16 834
5 268
11 269
7 739
1000

Вывод:
70
55 42 45 44 34 52 43 6 9 53 59 67 13 27 30 12 70 66 39 24 54 14 26 8 40 20 29 23 64 51 58 18 47 65 19 10 4 41 16 63 21 32 1 49 57 38 15 62 28 11 31 56 69 68 25 22 37 61 17 7 46 50 36 60 2 33 35 3 48 5

**F. Рюкзак: наибольший вес**
Дано N золотых слитков массой m1, …, mN. Ими наполняют рюкзак, который выдерживает вес не более M. Какую наибольшую массу золота можно унести в таком рюкзаке?

**Формат ввода**
В первой строке вводится натуральное число N, не превышающее 100 и натуральное число M, не превышающее 10000.

Во второй строке вводятся N натуральных чисел mi , не превышающих 100.

**Формат вывода**
Выведите одно целое число - наибольшую возможную массу золота, которую можно унести в данном рюкзаке.

**Пример**
Ввод: 
1 5968
18

Вывод:
18

In [ ]:
n, m = map(int, input().split())
s = [0] + list(map(int, input().split()))
data = [[False] * (m + 1) for _ in range(n + 1)]
data[0][0] = True
for i in range(1, n + 1):
    for j in range(m + 1):
        data[i][j] = data[i - 1][j]
        if s[i] <= j and data[i - 1][j - s[i]]:
            data[i][j] = True
ans = []
for i in range(m + 1):
    if data[n][i]:
        ans.append(i)
print(max(ans))

**G. Рюкзак: наибольшая стоимость**
Дано N предметов массой m1, …, mN и стоимостью c1, …, cN соответственно.

Ими наполняют рюкзак, который выдерживает вес не более M. Какую наибольшую стоимость могут иметь предметы в рюкзаке?

**Формат ввода**
В первой строке вводится натуральное число N, не превышающее 100 и натуральное число M, не превышающее 10000.

Во второе строке вводятся N натуральных чисел mi, не превышающих 100.

Во третьей строке вводятся N натуральных чисел ci, не превышающих 100.

**Формат вывода**
Выведите наибольшую стоимость рюкзака.

**Пример**
Ввод: 
1 597
18
16

Вывод:
16

In [ ]:
n, m = map(int, input().split())
s = [0] + list(map(int, input().split()))
costs = [0] + list(map(int, input().split()))
data = [[0] * (m + 1) for _ in range(n + 1)]

for i in range(1, n + 1):
    for j in range(m + 1):
        data[i][j] = data[i - 1][j]
        if s[i] <= j:
            data[i][j] = max(data[i][j], data[i - 1][j - s[i]] + costs[i])
print(max(data[n]))

**H. Рюкзак: наибольшая стоимость с восстановлением ответа**
Дано N предметов массой m1, …, mN и стоимостью c1, …, cN соответственно.

Ими наполняют рюкзак, который выдерживает вес не более M. Определите набор предметов, который можно унести в рюкзаке, имеющий наибольшую стоимость.

**Формат ввода**
В первой строке вводится натуральное число N, не превышающее 100 и натуральное число M, не превышающее 10000.

Во второй строке вводятся N натуральных чисел mi, не превышающих 100.

В третьей строке вводятся N натуральных чисел ci, не превышающих 100.

**Формат вывода**
Выведите номера предметов (числа от 1 до N), которые войдут в рюкзак наибольшей стоимости.

**Пример**
Ввод: 
4 6
2 4 1 2
7 2 5 1

Вывод:
1
3
4

In [ ]:
def history(i, j):
    global ans
    res = []
    while i > 0 and j > 0:
        t = j - s[i - 1]
        if data[i - 1][j] != data[i][j]:
            res.append(i)
            i -= 1
            j = t
            ans = data[i][j]
        else:
            i -= 1
    return res


n, m = map(int, input().split())
s = list(map(int, input().split()))
costs = list(map(int, input().split()))
data = [[-1] * (m + 1)]
data[0][0] = 0
for i in range(n):
    data += [[0] * (m + 1)]
    for j in range(m + 1):
        data[-1][j] = data[-2][j]
    for j in range(m - s[i], -1, -1):
        b = data[-1][j] != -1
        if b and data[-1][j + s[i]] < data[-1][j] + costs[i]:
            data[-1][j + s[i]] = data[-1][j] + costs[i]
ans = max(data[-1])
pos = 0
for i in range(len(data[-1])):
    if data[-1][i] == ans:
        pos = i
print(*history(n, pos)[::-1], sep="\n")

**I. Дизайнерский лифт**
Дизайн-студия Артемия Индюкова получила заказ на разработку очень пафосного лифта для нового небоскреба. За работу взялся сам Артемий, отличающейся, кстати, редкой неадекватностью. У него есть идея-фикс: для управления лифтом достаточно четырех кнопок. Кнопки должны быть следующие:

- Поднятся на A этажей вверх

- Поднятся на B этажей вверх

- Поднятся на C этажей вверх

- Спустится на первый этаж

Изначально лифт находится на первом этаже. Пассажир лифта использует первые три кнопки чтобы попасть на тот этаж, на который он хочет. Если пассажир пытается подняться вверх на A, B или C этажей, а такого этажа в здании не существует (т.е. пассажир хочет подняться выше N-го, последнего этажа), то лифт никуда не едет.

Заказчики проекта оказались с юмором и вместе с отказом от футуристичного дизайна решили оценить адекватность Артемия по шкале от 1 до N. Оценка адеватности равна количеству этажей, на которые можно попасть с первого с помощью такого лифта. Помогите им в этом.

**Формат ввода**
Первая строка содержит число N – высоту небоскреба (1 <= N <= 500 000).

Вторая строка содержит три числа A, B и C, задающие параметры кнопок (1 <= A, B, C <= 100 000).

**Формат вывода**
Выведите единственное число — оценку адекватности Артемия Индюкова.

**Пример**
Ввод: 
15
4 7 9

Вывод:
9

In [ ]:
n = int(input())
a, b, c = map(int, input().split())
data = [0] * (n + 1)
data[1] = 1
for i in range(n, -1, -1):
    if data[i] == 1:
        if i + b < n + 1:
            data[i + b] = 1
for j in range(4):
    delt = 0
    if j == 0: delt = c
    elif j == 1: delt = b
    elif j == 2: delt = a
    elif j == 3: delt = c
    for i in range(n + 1):
        if data[i] == 1:
            if i + delt < n + 1:
                data[i + delt] = 1
print(sum(data))

**J. Две стены**
У Пети есть набор из N кирпичиков. Каждый кирпичик полностью окрашен в один из K цветов, i-й кирпичик имеет размер 1×1×Li. Петя знает, что он может построить из кирпичиков прямоугольную стену толщиной 1 и высотой K, причем первый горизонтальный слой кирпичиков в стене будет первого цвета, второй - второго и т. д. Теперь Петя хочет узнать, может ли он из своего набора построить две прямоугольные стены, обладающие тем же свойством. Помогите ему выяснить это.

**Формат ввода**
В первой строке входных данных задаются числа N и K (1 <= N <= 5000, 1 <= K <= 100). Следующие N строк содержат описание Петиных кирпичиков: сначала длина Li, затем номер цвета Ci (1 <= Li <= 100, 1 <= Ci <= K). Известно, что у Пети не более 50 кирпичиков каждого цвета.

**Формат вывода**
Выведите в первой строке YES, если Петя сможет построить из своих кирпичиков две прямоугольные стены высоты K, j-й слой кирпичиков в каждой из которых будет j-го цвета, и NO в противном случае. В случае положительного ответа, выведите во второй строке в произвольном порядке номера кирпичиков, из которых следует построить первую стену (кирпичики нумеруются в том порядке, в котором они заданы во входных данных, начиная с 1). Если решений несколько, можно выдать любое из них.

**Пример**
Ввод: 
3 1
1 1
2 1
3 1

Вывод:
YES
1